### ISSUE TITLE
"Failed to crate tls config, because of open /etc/kubernetes/pki/etcd/etcd-client.pem: no such file or directory" 

### ISSUE THREAD

**Issue by hepyu** [ringtail/lucas#10]
time="2020-02-25T13:31:59Z" level=panic msg="Failed to crate tls config, because of open /etc/kubernetes/pki/etcd/etcd-client.pem: no such file or directory"

**Comment by ringtail** [comment]
> time="2020-02-25T13:31:59Z" level=panic msg="Failed to crate tls config, because of open /etc/kubernetes/pki/etcd/etcd-client.pem: no such file or directory"

Is the cluster on ACK?
