### ISSUE TITLE
大神可以修复下view乱码问题吗

### ISSUE THREAD

**Issue by hctaler** [ringtail/lucas#3]
�

**Comment by hctaler** [comment]
最好优化下显示

**Comment by ringtail** [comment]
@hctaler 好的，我先看下怎么改下

**Comment by ringtail** [comment]
@hctaler 我看了下大部分是configmap和rolebinding的位置，你发现的乱码在哪

**Comment by hctaler** [comment]
> @hctaler 我看了下大部分是configmap和rolebinding的位置，你发现的乱码在哪

我看我的感觉都有，不止这两个地方

**Comment by ringtail** [comment]
@hctaler 确认了下存储的元数据本身是有特殊字符的，并非解码问题
